run:
  concurrency: 4
  timeout: 5m

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - maligned
    - ifshort
    - interfacer
    - deadcode
    - scopelint
    - varcheck
    - golint
    - nosnakecase
    - structcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    - gochecknoglobals
    - exhaustruct
    - varnamelen
    - wrapcheck
    - gofumpt
    - errorlint
    - gci
    - goimports