
services:
  go:
    build: .

  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=private
      - POSTGRES_USER=private
      - POSTGRES_PASSWORD=private
    volumes:
      - ~/.pgc-postgres:/var/lib/postgresql/data
    ports:
      - "6543:5432"