name: GO Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        uses: golangci/golangci-lint-action@v3.4.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
